### ISSUE TITLE
Great Codes! ~

### ISSUE THREAD

**Issue by yuchenlin** [suidanyang/NumGuess#1]
This program is correct and pretty easy to read. I believe that there are 2 main features of it.

1st Great command of syntax. The developer used three while loops to generate 3 different random numbers. It's effective and correct in this case.

2nd The two lines of core code is easy to understand. Regardless of the fact that they are pretty long, it's okay and acceptable for beginning learners to use this kind of syntax. I believe when you have more experience of programming your code will be shorter.

All in a word, I think this program is pretty good. I'm looking forward to your next homework and your progress. ^ ^~

**Comment by suidanyang** [comment]
Thank you!!!
