### ISSUE TITLE
Good work!

### ISSUE THREAD

**Issue by qu10wenhao** [suidanyang/NumGuess#2]
the developer achieves the goal with short and efficient codes. And the English notes help people have a good understanding. The information for the users has a little humorous which can attract the users.
There are some advices from me. 
First, if the developer add space before and after the operations such as '<<', '>>', the codes may be more comfortable.
Second, the way to judge the values of A and B is not so good. it wiil be very unconvenient if there are more random numbers.
In all, it's still a very good program. Well done!

**Comment by suidanyang** [comment]
Thank you!!!
