### ISSUE TITLE
Comments from RaleighHan

### ISSUE THREAD

**Issue by RaleighHan** [suidanyang/NumGuess#3]
At first, I have to say that you have done a vey good job in this coding. I believe that you will achieve more in the following programming. 

What impresses me most is your variable-names, which are easy to understand. The way you think about this problem is also very clear, while your code is not very long. That' really a good point.

However, you seem to have a problem in line 27. You must have forgotten to delete it when finishing debugging. Fix it, and it will be a very perfect piece of code.

**Comment by suidanyang** [comment]
Thank you!!!
